---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	first_run_router(first_run_router)
	llm_first_pass(llm_first_pass)
	task_classification(task_classification)
	router(router)
	rag_lookup(rag_lookup)
	tz_extractor(tz_extractor)
	completeness_check(completeness_check)
	human_input(human_input)
	validation(validation)
	code_generation(code_generation)
	__end__([<p>__end__</p>]):::last
	__start__ --> first_run_router;
	code_generation --> __end__;
	completeness_check --> router;
	human_input --> router;
	llm_first_pass --> router;
	rag_lookup --> completeness_check;
	task_classification --> llm_first_pass;
	tz_extractor --> completeness_check;
	validation --> code_generation;
	first_run_router -. &nbsp;first_run&nbsp; .-> task_classification;
	first_run_router -. &nbsp;human_input_needed&nbsp; .-> human_input;
	first_run_router -. &nbsp;subsequent_run&nbsp; .-> router;
	router -. &nbsp;need_table&nbsp; .-> rag_lookup;
	router -. &nbsp;need_tz&nbsp; .-> tz_extractor;
	router -. &nbsp;ask_human&nbsp; .-> human_input;
	router -.-> completeness_check;
	router -. &nbsp;done&nbsp; .-> validation;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
